apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-ollama-results-pvc
  namespace: ollama-inference
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: lvms-vg1
